WORD = "синхрофазотрон"
RESULT_FILE_NAME = 'list_of_results.json'
RESULT_FILE_NAME_TEST = 'TEST_list_of_results.json'

WORD_SIZE = 35
GAME_FIELD_FONT_SIZE=16
START_WINDOW_STATISTICK_FONT_SIZE=16
START_PAGE_FONT = 30

TIMER_VALUE = 300